version: '2'
services:
  tensorflow:
    build: ./docker/tensorflow/
    environment:
     - PASSWORD=password
    ports:
     - "8888:8888"
    volumes:
     - ./notebooks/:/notebooks/
  tensorboard:
    build: ./docker/tensorboard/
    ports:
     - "6006:6006"
    volumes:
     - ./notebooks/logs/:/tensorflow-logs/
